# Instance types, hosts per zone, partitions per device
# You may wish to change these
# =================================

# All AWS assets will be identified using this prefix + appropriate suffix. See constants.yml for more details.
cluster_identifier: aerospike

cluster_instance_type: c5d.large
cluster_hosts_per_az : 1
partitions_per_device: 4

# Aerospike client type and count
client_instance_type: "{{ cluster_instance_type }}"
aerospike_client_per_az_count: 1

# Aerospike monitoring type
monitoring_instance_type: "{{ cluster_instance_type }}"

# Spark worker count
spark_instance_type: "{{ cluster_instance_type }}"
spark_worker_per_az_count: 1

# Kafka instance type & number
kafka_instance_type: "{{ cluster_instance_type }}"
kafka_worker_per_az_count: 1

# Installation configuration
# ===================================

# Whether to use enterprise
# Set to false by default so will run without features.conf
enterprise: false

# Whether to enable encryption at rest
encryption_at_rest: false

# Whether to use TLS
tls_enabled: false

# Strong consistency
strong_consistency: false

# All Flash
all_flash: false

# Monitoring
monitoring_enabled: true

# Kafka Connect
kafka_connect_enabled: false

# Version number
aerospike_version: "latest" 
# Use full version number e.g. 4.8.0.8 'latest' is also recognized. 

# Client version number
aerospike_tools_version: "7.0.3"

# Prometheus exporter version
prometheus_exporter_version: "1.7.0"

# Operating system - use ubuntu_os or amzn_linux_os inside the curly braces
# This will determine the Aerospike distribution and ami used
# Also remote user
operating_system: "{{ amzn_linux_os }}"

# Replication factor
replication_factor: 2

# Proportion of total memory to assign to Aerospike - used in configuration template - see assets folder
aerospike_mem_pct: 80

# Cluster ID - used by Prometheus exporter
cluster_batch_tag: "CL01"

# Do not change the configuration below - it is driven by the choice of operating system
# ======================================================================================

# Distribution
aerospike_distribution: "{{ os_config['aerospike_distribution'] }}" 

# AMI - will use the most recent AMI matching the name below
ami_locator_string: "{{ os_config['ami_locator_string'] }}"

# Default user for instances - varies depending on OS choice
remote_user: "{{ os_config['remote_user'] }}"


